# Generated by Django 4.2.6 on 2023-12-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='member3.png', upload_to='profile_avatars'),
        ),
    ]
