# Generated by Django 4.2.6 on 2023-11-28 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0010_account_emailaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account_emailaddress',
        ),
    ]
