# Generated by Django 4.2.6 on 2023-12-02 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0016_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='BillingDetails',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
