# Generated by Django 4.2.6 on 2024-01-10 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0021_verification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
